name = "tribal-wall"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tribal-wall-db"
database_id = "local"

[triggers]
crons = ["0 * * * *"]
